# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-23 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=1024)),
                ('refresh_token', models.CharField(max_length=1024)),
                ('access_token_created_at', models.DateTimeField(auto_now_add=True)),
                ('refresh_token_created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField(default=0)),
            ],
        ),
    ]
